---
title: '20200415'
output: html_document
---

```{r}
listExample <-
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
```


```{r}
`108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
```

```{r}
str(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
```

```{r}
get1<-listExample[["學期"]] # 拿出來
get1<-listExample$`學期` # 拿出來
get2<-listExample["學期"] # 只留下
```

### get1 取出
```{r}
get1$`108-1` ->get1_layer1; get1_layer1
get1_layer1[[1]] ->get1_layer2; get1_layer2
get1_layer2$teacher
```

```{r}
get1<-listExample[["學期"]] # 拿出來
get1$`108-1` ->get1_layer1; get1_layer1
get1_layer1[[1]] ->get1_layer2; get1_layer2
get1_layer2$teacher

get1$`108-1`[[1]]$teacher
```

### get2 取出
```{r}
get2<-listExample["學期"]
get2_layer1 <-get2[[1]]
get2_layer2 <-get2_layer1[["108-1"]]
get2_layer3 <-get2_layer2[[1]]
get2_layer3$teacher
```

```{r}
listExample["學期"][[1]][["108-1"]][[1]]$teacher
listExample["學期"][["學期"]][["108-1"]][[1]]$teacher
```

#### list應用
```{r}
vector1 <-c(a=1,b=3,c=4)
vector1[["a"]]
vector1[c("a","c")]
vector1$a

list1 <- list(a=1,b=3,c=4)
list1[["a"]]
list1[c("a","c")]
list1$a
```

今明兩日台北市、新北市氣溫：
```{r}
today <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
str(today)
```
```{r}
today <- list(
  list("台北市",
       highest_temp=c(highest_temp = 25),
       lowest_temp=c(lowest_temp = 18)),
  list("新北市",
       highest_temp=c(highest_temp = 24),
       lowest_temp=c(lowest_temp = 15)))
str(today)
```

```{r}
today[[1]]$highest_temp
```

```{r}
tomorrow <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))

weather <- list(today,tomorrow)

print(weather)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

